Feature/create select internal label
aiqfome/aiq-design-system pull request #486
Opened 2024-04-15 19:12 UTC by lucasAiq

2024-04-15 19:27 UTC, erickaguilaraiq requested changes

2024-04-15 19:27 UTC, erickaguilaraiq commented on package.json
não precisa alterar a versão, é feito de forma automática quando mergeamos na master

2024-04-15 19:27 UTC, erickaguilaraiq commented on yarn-error.log
esse yarn-error aqui acho que era pra estar no `.gitignore` kkkkk
```
// .gitignore

yarn-error.log*
```

2024-04-15 20:38 UTC, erickaguilaraiq approved these changes

2024-04-16 12:42 UTC, MrsBolinhu approved these changes

2024-04-16 12:43 UTC, Nhed1 approved these changes

2024-04-16 13:31 UTC, merged